import Foundation

private let generatorNote = "This file is auto-generated by `.github/scripts/generate-public-api-list.sh`."

private struct SymbolEntry {
    let precise: String
    let group: String
    let title: String
    let signature: String
    var availabilityByDomain: [String: String]
}

private enum Mode {
    case write
    case check
}

private struct Configuration {
    let symbolGraphsDirectory: URL
    let apiFilePath: URL
    let mode: Mode
}

private func fail(_ message: String) -> Never {
    fputs("error: \(message)\n", stderr)
    exit(1)
}

private func parseArguments() -> Configuration {
    var arguments = Array(CommandLine.arguments.dropFirst())
    var symbolGraphsDirectory: URL?
    var apiFilePath: URL?
    var mode: Mode = .write

    while !arguments.isEmpty {
        let argument = arguments.removeFirst()
        switch argument {
        case "--symbol-graphs-dir":
            guard !arguments.isEmpty else {
                fail("Missing value for --symbol-graphs-dir")
            }
            symbolGraphsDirectory = URL(fileURLWithPath: arguments.removeFirst())
        case "--apis-file":
            guard !arguments.isEmpty else {
                fail("Missing value for --apis-file")
            }
            apiFilePath = URL(fileURLWithPath: arguments.removeFirst())
        case "--check":
            mode = .check
        case "--write":
            mode = .write
        default:
            fail("Unknown argument: \(argument)")
        }
    }

    guard let symbolGraphsDirectory else {
        fail("Argument --symbol-graphs-dir is required")
    }

    guard let apiFilePath else {
        fail("Argument --apis-file is required")
    }

    return Configuration(
        symbolGraphsDirectory: symbolGraphsDirectory,
        apiFilePath: apiFilePath,
        mode: mode
    )
}

private func fileURLs(in directory: URL) -> [URL] {
    guard let enumerator = FileManager.default.enumerator(
        at: directory,
        includingPropertiesForKeys: nil,
        options: [.skipsHiddenFiles]
    ) else {
        return []
    }

    return enumerator.compactMap { item in
        guard let url = item as? URL else { return nil }
        return url.pathExtension == "json" ? url : nil
    }
}

private func string(from declarationFragments: Any?) -> String? {
    guard let fragments = declarationFragments as? [[String: Any]] else {
        return nil
    }

    let output = fragments.compactMap { fragment -> String? in
        fragment["spelling"] as? String
    }.joined()

    return output.isEmpty ? nil : output
}

private func normalizedWhitespace(_ string: String) -> String {
    string
        .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
        .trimmingCharacters(in: .whitespacesAndNewlines)
}

private func normalizedSignature(_ signature: String) -> String {
    var result = normalizedWhitespace(signature)

    while result.hasPrefix("public ") || result.hasPrefix("open ") {
        if result.hasPrefix("public ") {
            result.removeFirst("public ".count)
        } else if result.hasPrefix("open ") {
            result.removeFirst("open ".count)
        }
        result = normalizedWhitespace(result)
    }

    return result
}

private func fallbackSignature(kindIdentifier: String, title: String) -> String {
    if kindIdentifier.contains("func") {
        return "func \(title)"
    }
    if kindIdentifier.contains("property") || kindIdentifier.contains("var") {
        return "var \(title)"
    }
    if kindIdentifier.contains("enum") {
        return "enum \(title)"
    }
    if kindIdentifier.contains("struct") {
        return "struct \(title)"
    }
    if kindIdentifier.contains("class") {
        return "class \(title)"
    }
    if kindIdentifier.contains("protocol") {
        return "protocol \(title)"
    }
    if kindIdentifier.contains("typealias") {
        return "typealias \(title)"
    }
    if kindIdentifier.contains("init") {
        return "init\(title)"
    }
    return title
}

private func versionString(from introduced: [String: Any]) -> String? {
    guard let major = introduced["major"] as? Int else {
        return nil
    }
    let minor = introduced["minor"] as? Int ?? 0
    let patch = introduced["patch"] as? Int ?? 0

    if patch > 0 {
        return "\(major).\(minor).\(patch)"
    }
    if minor > 0 {
        return "\(major).\(minor)"
    }
    return "\(major)"
}

private func versionComponents(_ version: String) -> [Int] {
    let components = version.split(separator: ".").map { Int($0) ?? 0 }
    if components.count >= 3 {
        return Array(components.prefix(3))
    }
    if components.count == 2 {
        return [components[0], components[1], 0]
    }
    if components.count == 1 {
        return [components[0], 0, 0]
    }
    return [0, 0, 0]
}

private func lowerVersion(_ lhs: String, _ rhs: String) -> String {
    let left = versionComponents(lhs)
    let right = versionComponents(rhs)
    if left.lexicographicallyPrecedes(right) {
        return lhs
    }
    return rhs
}

private func availabilityByDomain(from availability: Any?) -> [String: String] {
    guard let availabilityEntries = availability as? [[String: Any]] else {
        return [:]
    }

    var output: [String: String] = [:]
    let supportedDomains = Set(["iOS", "tvOS", "watchOS", "macOS"])

    for entry in availabilityEntries {
        guard let domain = entry["domain"] as? String, supportedDomains.contains(domain) else {
            continue
        }
        guard let introduced = entry["introduced"] as? [String: Any], let version = versionString(from: introduced) else {
            continue
        }

        if let existing = output[domain] {
            output[domain] = lowerVersion(existing, version)
        } else {
            output[domain] = version
        }
    }

    return output
}

private func isBackportFacing(pathComponents: [String], title: String) -> Bool {
    if pathComponents.contains("Backport") {
        return true
    }
    if pathComponents.contains("EnvironmentValues") {
        return true
    }
    if title == "backport" || title.hasPrefix("backport") {
        return true
    }
    if let last = pathComponents.last, last == "backport" || last.hasPrefix("backport") {
        return true
    }
    return false
}

private func groupName(pathComponents: [String], title: String, signature: String, kindIdentifier: String) -> String {
    if pathComponents.contains("EnvironmentValues") || (title.hasPrefix("backport") && signature.contains("EnvironmentValues")) {
        return "Environment Backports"
    }
    if title == "backport", pathComponents.contains("View") {
        return "View Namespace"
    }
    if title == "backport", pathComponents.contains("AnyTransition") {
        return "Transition Namespace"
    }
    if pathComponents.contains("Backport") {
        if kindIdentifier.contains("func")
            || kindIdentifier.contains("subscript")
            || signature.hasPrefix("func ")
            || signature.hasPrefix("subscript")
        {
            return "Modifiers"
        }
        return "Backport Namespace"
    }
    return "Other Backport API"
}

private func loadSymbolEntries(from file: URL) -> [SymbolEntry] {
    guard let data = try? Data(contentsOf: file) else {
        fail("Unable to read symbol graph file at \(file.path)")
    }

    guard let raw = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
        fail("Unable to decode JSON in \(file.path)")
    }

    guard let symbols = raw["symbols"] as? [String: Any] else {
        return []
    }

    var output: [SymbolEntry] = []

    for (_, symbolValue) in symbols {
        guard let symbol = symbolValue as? [String: Any] else { continue }

        guard let accessLevel = symbol["accessLevel"] as? String,
              accessLevel == "public" || accessLevel == "open"
        else {
            continue
        }

        guard let identifier = symbol["identifier"] as? [String: Any],
              let precise = identifier["precise"] as? String
        else {
            continue
        }

        let names = symbol["names"] as? [String: Any]
        let title = (names?["title"] as? String)?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? ""
        let pathComponents = symbol["pathComponents"] as? [String] ?? []

        guard isBackportFacing(pathComponents: pathComponents, title: title) else {
            continue
        }

        let kind = symbol["kind"] as? [String: Any]
        let kindIdentifier = kind?["identifier"] as? String ?? ""

        let declaration = string(from: symbol["declarationFragments"])
            ?? string(from: names?["subHeading"])
            ?? fallbackSignature(kindIdentifier: kindIdentifier, title: title)

        let signature = normalizedSignature(declaration)
        guard !signature.isEmpty else { continue }

        let availability = availabilityByDomain(from: symbol["availability"])

        output.append(
            SymbolEntry(
                precise: precise,
                group: groupName(
                    pathComponents: pathComponents,
                    title: title,
                    signature: signature,
                    kindIdentifier: kindIdentifier
                ),
                title: title,
                signature: signature,
                availabilityByDomain: availability
            )
        )
    }

    return output
}

private func mergedEntries(_ entries: [SymbolEntry]) -> [SymbolEntry] {
    var byPrecise: [String: SymbolEntry] = [:]

    for entry in entries {
        if var existing = byPrecise[entry.precise] {
            for (domain, version) in entry.availabilityByDomain {
                if let current = existing.availabilityByDomain[domain] {
                    existing.availabilityByDomain[domain] = lowerVersion(current, version)
                } else {
                    existing.availabilityByDomain[domain] = version
                }
            }

            if entry.signature.count > existing.signature.count {
                byPrecise[entry.precise] = SymbolEntry(
                    precise: existing.precise,
                    group: existing.group,
                    title: existing.title,
                    signature: entry.signature,
                    availabilityByDomain: existing.availabilityByDomain
                )
            } else {
                byPrecise[entry.precise] = existing
            }
        } else {
            byPrecise[entry.precise] = entry
        }
    }

    return Array(byPrecise.values)
}

private func availabilityLine(for availabilityByDomain: [String: String]) -> String? {
    let domainOrder = ["iOS", "tvOS", "watchOS", "macOS"]
    let parts = domainOrder.compactMap { domain -> String? in
        guard let version = availabilityByDomain[domain] else { return nil }
        return "\(domain) \(version)"
    }

    guard !parts.isEmpty else {
        return nil
    }

    return "@available(\(parts.joined(separator: ", ")), *)"
}

private func generatedDocument(from entries: [SymbolEntry]) -> String {
    let groupOrder = [
        "View Namespace",
        "Transition Namespace",
        "Environment Backports",
        "Modifiers",
        "Backport Namespace",
        "Other Backport API"
    ]

    let grouped = Dictionary(grouping: entries, by: { $0.group })
    let allGroups = Array(grouped.keys)
    let sortedGroups = allGroups.sorted { lhs, rhs in
        let left = groupOrder.firstIndex(of: lhs) ?? Int.max
        let right = groupOrder.firstIndex(of: rhs) ?? Int.max
        if left == right { return lhs < rhs }
        return left < right
    }

    var lines: [String] = [
        "# Available APIs",
        "",
        generatorNote,
        "",
        "## Public API",
        ""
    ]

    var hasAtLeastOneEntry = false
    for group in sortedGroups {
        guard let symbols = grouped[group], !symbols.isEmpty else {
            continue
        }
        hasAtLeastOneEntry = true

        lines.append("### \(group)")
        lines.append("")

        let orderedSymbols = symbols.sorted {
            if $0.title == $1.title {
                if $0.signature == $1.signature {
                    return $0.precise < $1.precise
                }
                return $0.signature < $1.signature
            }
            return $0.title < $1.title
        }

        for symbol in orderedSymbols {
            if let availability = availabilityLine(for: symbol.availabilityByDomain) {
                lines.append("- `\(availability)`  ")
                lines.append("  `\(symbol.signature)`")
            } else {
                lines.append("- `\(symbol.signature)`")
            }
        }

        lines.append("")
    }

    if !hasAtLeastOneEntry {
        lines.append("_No API entries generated._")
    }

    return lines.joined(separator: "\n")
}

private func run() {
    let configuration = parseArguments()
    let symbolGraphFiles = fileURLs(in: configuration.symbolGraphsDirectory)

    if symbolGraphFiles.isEmpty {
        fail("No symbol graph JSON files found at \(configuration.symbolGraphsDirectory.path)")
    }

    let allEntries = symbolGraphFiles.flatMap(loadSymbolEntries(from:))
    let entries = mergedEntries(allEntries)
    let generated = generatedDocument(from: entries)

    let existingAPIDocument: String
    do {
        existingAPIDocument = try String(contentsOf: configuration.apiFilePath, encoding: .utf8)
    } catch {
        existingAPIDocument = ""
    }

    let changed = generated != existingAPIDocument

    switch configuration.mode {
    case .write:
        if changed {
            do {
                try generated.write(to: configuration.apiFilePath, atomically: true, encoding: .utf8)
                print("Updated APIs.md public API list.")
            } catch {
                fail("Unable to write updated API file at \(configuration.apiFilePath.path)")
            }
        } else {
            print("APIs.md public API list is already up to date.")
        }
    case .check:
        if changed {
            print("APIs.md public API list is out of date.")
            exit(2)
        } else {
            print("APIs.md public API list is up to date.")
        }
    }
}

run()
